version: "3.9"

services:
  postgres-balance:
    image: postgres
    environment:
      POSTGRES_DB: "balanceDB"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "postgresql"
    ports:
      - 5434:5432
